### ISSUE TITLE
" \xe2\x96\x88 " reported as invalid

### ISSUE THREAD

**Issue by nomeata** [chansen/c-utf8-valid#1]
It seems that if I add the following lines to `test.c`:
```
  char src[]=" \xe2\x96\x88 ";
  TEST_UTF8(src, 5, 0, true);
```
I get
```
$ cc test.c -o test && ./test 
utf8_valid(" \xE2\x96\x88 ", 5) != true at line 293
Failed 1 tests of 4381826.
```

I believe the problem is related this line in `utf8_valid.h`, which I would expect should look maybe as  follows:
```diff
--- a/utf8_valid.h
+++ b/utf8_valid.h
@@ -70,7 +70,8 @@ utf8_check(const char *src, size_t len, size_t *cursor) {
   unsigned char buf[4];
   uint32_t v;
 
-  for (p = cur;;) {
+  while (1) {
+    p = cur;
     if (cur >= end - 3) {
       if (cur == end)
         break;
```

Else, for strings larger than 4 characters, `p` is always pointing to the _first_ character.

**Comment by jeking3** [comment]
This issue also affects:
utf8_valid(" \xEF\xBF\xBD ", 5) != true at line 298
i.e. unicode \uFFFD
